name: Module checks
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  check:
    uses: kyuhank/cpue-actions-demo/.github/workflows/module-check.yml@db2b3a8e59ac88fb11a3763d23ee48e82d883570
    with:
      repository: ${{ github.repository }}
      commit: ${{ github.sha }}
      harness: db2b3a8e59ac88fb11a3763d23ee48e82d883570
